<?php
/**
 * @file
 * Generates custom blocks.
 */

/**
 * Implements hook_block_info()
 * @return array
 */
function afaa_blocks_block_info() {
  return array(
    'afaa_block_support' => array(
      'info' => 'Support Us',
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
    'afaa_block_connect' => array(
      'info' => 'Connect With Us',
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
    'afaa_block_facebook' => array(
      'info' => 'AFAA on Facebook',
      'cache' => DRUPAL_CACHE_GLOBAL,
    ),
  );
}


/**
 * Implements hook_block_configure().
 * @param string $delta
 * @return array
 */
function afaa_blocks_block_configure($delta = '') {
  if (strpos($delta, 'afaa_') !== 0) {
    return array();
  }

  // A little meta-programming never hurt anyone, right?
  $function = 'afaa_blocks_block_' . $delta . '_configure';

  if (is_callable($function)) {
    return $function();
  }

  return array();
}


/**
 * Generates a form to configure the "connect" block.
 * @return array
 */
function afaa_blocks_block_afaa_block_connect_configure() {
  $settings = variable_get('afaa_block_connect', array());
 
  $form = array(
    'settings' => array(
      '#tree' => true,
    ),
  ); 

  $form['settings']['body'] = array(
    '#type' => 'text_format',
    '#format' => null,
    '#default_value' => isset($settings['body']['value']) ? $settings['body']['value'] : null,
    '#format' => isset($settings['body']['format']) ? $settings['body']['format'] : null,
    '#title' => t('Body'),
    '#description' => t('Custom content that shows up beneath the block title,')
  );

  return $form;
}

/**
 * Generates a form to configure the "support" block.
 * @return array
 */
function afaa_blocks_block_afaa_block_support_configure() {
  $settings = variable_get('afaa_block_support', array());
  $form = array(
    'settings' => array(
      '#tree' => true,
    ),
  ); 

  $form['settings']['body'] = array(
    '#type' => 'text_format',
    '#default_value' => isset($settings['body']['value']) ? $settings['body']['value'] : null,
    '#format' => isset($settings['body']['format']) ? $settings['body']['format'] : null,
    '#title' => t('Body'),
    '#description' => t('Custom content that shows up beneath the block title,')
  );

  return $form;
}


/**
 * Implements hook_block_block_save()
 * @param string $delta
 * @param aray $edit
 */
function afaa_blocks_block_save($delta = '', $edit = array()) {
  if (strpos($delta, 'afaa_') !== 0) {
    return;
  }
  if (! empty($edit) && isset($edit['settings'])) {
    variable_set($delta, $edit['settings']);
  }
}


/**
 * Implements hook_block_view()
 * @param string $delta
 */
function afaa_blocks_block_view($delta = '') {
  if (strpos($delta, 'afaa_') !== 0) {
    return;
  }
  
  $function = 'afaa_blocks_block_' . $delta . '_view';

  if (is_callable($function)) {
    return $function();
  }

  return array(
     'subject' => t('AFAA Block'),
     'content' => array(),
  );
}


/**
 * Metafunction to generate content for the facebook block.
 */
function afaa_blocks_block_afaa_block_facebook_view() {
  return array(
    'subject' => t('AFAA on Facebook'),
    'content' => array(),
  );
}

/**
 * Metafunction to generate content for the "connect with us" block.
 */
function afaa_blocks_block_afaa_block_connect_view() {
  $settings = variable_get('afaa_block_connect', array());
  return array(
    'subject' => t('Connect With Us'),
    'content' => array(
      '#markup' => $settings['body']['value'],
      'format' => $settings['body']['format'],
    ),
  );
}

/**
 * Metafunction to generate content for the "support us" block.
 */
function afaa_blocks_block_afaa_block_support_view() {
  $settings = variable_get('afaa_block_support', array());
  return array(
    'subject' => t('Support Us'),
    'content' => array(
       'body' => array(
         '#markup' => $settings['body']['value'],
         'format' => $settings['body']['format'],
       ),
    ),
  );
}
